[package]
name = "lean-homotopy-theory"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "d4568a412425dd528b969446efc0452491ae8528"}
